export const MARKETING_MESSAGE = "Free Billing software only pay for Backup";
export const MARKETING_SLOGAN = "Digital India ka Digital Billing Partner";
export const BILLMENSOR_PROMO = "Generated by Billmensor - Free Billing Software (Pay only for Backup)";
